In [10]:
# !pip install docplex
# !pip install memory_profiler
# !pip install dwave-system
# !pip install gurobipy
# !pip install yfinance

Collecting ace_tools
  Downloading ace_tools-0.0-py3-none-any.whl (1.1 kB)
Installing collected packages: ace_tools
Successfully installed ace_tools-0.0

WARNING: Ignoring invalid distribution -rotobuf (c:\users\aruna\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\aruna\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\aruna\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\aruna\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\aruna\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\aruna\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\aruna\anaconda3\lib\site-packages)

In [2]:
###############################################################################
# // SPDX-License-Identifier: Apache-2.0
# // Copyright 2024: Amazon Web Services, Inc. - Contributions from JPMC
###############################################################################

import numpy as np
import pandas as pd
from itertools import product
import sys
sys.path.append("../")
from dcmppln.pipeline import Pipeline
from dcmppln.optimizer import GurobiOptimizer
from tests.input_data import InputData
from dcmppln.optimizer import SimulatedAnnealingDwave
import yfinance as yf
from typing import List

In [53]:
def download_data(stocks: List[str], start_date: str, end_date: str, period_step: int) -> pd.DataFrame:
    stock_data = {}
    for stock in stocks:
        ticker = yf.Ticker(stock)
        stock_data[stock] = ticker.history(start=start_date, end=end_date)["Close"][::period_step]
    return pd.DataFrame(stock_data)

def calculate_return(data: pd.DataFrame) -> pd.DataFrame:
    log_return = np.log(data / data.shift(1))
    return log_return.iloc[1:]  # Drop first row as it will have NaN

# List of stock markets
markets = {
    #"payment_processors": ["V", "MA", "PYPL", "AXP", "DFS", "FI", "GPN", "FIS", "SQ", "ADP"],
    #"defense_contractors": ["LMT", "RTX", "NOC", "GD", "BA", "HII", "TXT", "LDOS", "CW", "LHX"],
    "consumer_staples": ["PG", "KO", "PEP", "WMT", "COST", "CL", "MDLZ", "KHC", "TGT", "SYY"],
    #"cloud_computing": ["MSFT", "AMZN", "GOOGL", "CRM", "ORCL", "IBM", "NOW", "DDOG", "ZS", "PANW"],
    #"autonomous_vehicles": ["TSLA", "GM", "F", "GOOGL", "NVDA", "INTC", "MBLY", "APTIV", "TM", "LI"],
    #"ecommerce_giants": ["AMZN", "BABA", "SHOP", "WMT", "EBAY", "MELI", "JD", "SE", "PDD", "TGT"],
    #"biotech_innovators": ["BIIB", "REGN", "VRTX", "ILMN", "CRSP", "NTLA", "BEAM", "EDIT", "BMRN", "XBI"],
    #"metaverse_stocks": ["META", "RBLX", "U", "NVDA", "MSFT", "GOOGL", "DIS", "SONY", "AAPL", "MTTR"],
    #"cybersecurity_leaders": ["PANW", "FTNT", "CRWD", "ZS", "OKTA", "CHKP", "MSFT", "NET", "CYBR", "BUG"],
    "semiconductor_giants": ["NVDA", "AMD", "INTC", "TSM", "QCOM", "AVGO", "ASML", "TXN", "MU", "LRCX"],
    #"green_energy": ["TSLA", "PLUG", "ENPH", "SEDG", "FSLR", "RUN", "NEE", "BE", "BLDP", "ICLN"],
    #"space_exploration": ["SPCE", "RKLB", "BA", "LMT", "NOC", "IRDM", "AJRD", "MAXR", "AVAV", "UFO"],
    "tech_titans": ["AAPL", "MSFT", "NVDA", "AMZN", "GOOGL", "META", "TSLA", "QQQ", "VGT", "IGM"],
    "financial_giants": ["JPM", "BAC", "GS", "WFC", "C", "MS", "SCHW", "V", "MA", "XLF"],
    "retail_consumer": ["WMT", "TGT", "COST", "HD", "LOW", "ULTA", "NKE", "SBUX", "AMZN", "XRT"],
    "healthcare_leaders": ["UNH", "JNJ", "PFE", "MRK", "ABBV", "LLY", "BMY", "TMO", "ISRG", "XLV"],
    #"energy_utilities": ["XOM", "CVX", "BP", "OXY", "COP", "ENB", "KMI", "NEE", "DUK", "XLE"],
    "industrial_powerhouses": ["CAT", "GE", "HON", "DE", "LMT", "BA", "MMM", "RTX", "EMR", "XLI"],
    #"real_estate_reits": ["VNQ", "O", "SPG", "AMT", "CCI", "PSA", "VICI", "PLD", "WELL", "XLRE"],
    #"entertainment_media": ["DIS", "NFLX", "CMCSA", "WBD", "PARA", "SPOT", "EA", "ROKU", "FOXA", "XLC"],  # Replaced SONY with EA
    #"international_giants": ["BABA", "TSM", "ASML", "NVS", "SAP", "TM", "LVMUY", "RIO", "VALE", "IXUS"],
    "defensive_plays": ["KO", "PG", "JNJ", "MCD", "PEP", "WMT", "XLU", "VYM", "TLT", "VGIT"],
    }

# Define time period for analysis
start_date = "2010-07-01"
end_date = "2020-07-01"
period_step = 5  # Weekly changes

# Initialize dataframe to store results
results_df = pd.DataFrame(columns=["Distribution", "Market", "Optimizer", "Correlations", "Covariances", "Returns", "DCT"])

### 2a: MP Distribution

In [54]:
# Loop through each market and analyze the stocks
# 2a Run:
for market_name, stocks in markets.items():
    print(f"\nProcessing market: {market_name}")
    
    # Distribution Type:
    distribution = "MP Distribution"
    
    # Download stock price data
    dataset = download_data(stocks, start_date, end_date, period_step)

    # Compute log returns
    log_period_returns = calculate_return(dataset)

    # Compute average returns for each stock (mean of log returns)
    returns = log_period_returns.mean().to_numpy()

    # Compute covariance matrix of log returns
    covariances = log_period_returns.cov().to_numpy()

    # Compute correlation matrix of log returns
    correlations = log_period_returns.corr().to_numpy()

    # Print output shapes for verification
    print("Returns shape:", returns.shape)  # (10,)
    print("Covariance matrix shape:", covariances.shape)  # (10, 10)
    print("Correlation matrix shape:", correlations.shape)  # (10, 10)")

    # No Optimizer Run
    p = Pipeline(
        correlations,
        covariances,
        returns,
    )
    dct = p.run()

    # Add results to dataframe
    results_df = pd.concat([results_df, pd.DataFrame([[distribution, market_name, "None", correlations, covariances, returns, dct]], 
                                                      columns=results_df.columns)], ignore_index=True)

    # Run with Gurobi Optimizer
    p = Pipeline(
        correlations,
        covariances,
        returns, 
        optimize_func=GurobiOptimizer()
    )
    dct = p.run(run_optimizer=True)

    # Add results to dataframe
    results_df = pd.concat([results_df, pd.DataFrame([[distribution, market_name, "Gurobi", correlations, covariances, returns, dct]], 
                                                      columns=results_df.columns)], ignore_index=True)

    # Run with D-Wave Simulated Annealing
    p = Pipeline(
        correlations,
        covariances,
        returns, 
        optimize_func=SimulatedAnnealingDwave()
    )
    dct = p.run(run_optimizer=True)

    # Add results to dataframe
    results_df = pd.concat([results_df, pd.DataFrame([[distribution, market_name, "Dwave", correlations, covariances, returns, dct]], 
                                                      columns=results_df.columns)], ignore_index=True)

Processing market: consumer_staples
Returns shape: (10,)
Covariance matrix shape: (10, 10)
Correlation matrix shape: (10, 10)
Read LP format model from file temp.lp
Reading time = 0.00 seconds
obj: 1 rows, 10 columns, 10 nonzeros
Set parameter TimeLimit to value 300
Set parameter Threads to value 1
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 1 threads

Optimize a model with 1 rows, 10 columns and 10 nonzeros
Model fingerprint: 0x0584b323
Model has 55 quadratic objective terms
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e-03, 4e-03]
  QObjective range [6e-04, 4e-03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+00, 5e+00]
Found heuristic solution: objective -0.0032659
Presolve time: 0.00s
Presolved: 46 rows, 55 columns, 145 nonzeros
Variable types: 0 continuous, 55 integer (55 binary)

Root relaxation: objective -5.534067e-03, 25 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   -0.00553    0   16   -0.00327   -0.00553  69.4%     -    0s
H    0     0                      -0.0034188   -0.00553  61.9%     -    0s
     0     0     cutoff    0        -0.00342   -0.00342  0.00%     -    0s

Cutting planes:
  Gomory: 1
  MIR: 5
  Zero half: 12
  RLT: 8
  BQP: 42

Explored 1 nodes (64 simplex iterations) in 0.07 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 2: -0.00341879 -0.0032659

Optimal solution found (tolerance 1.00e-04)
Best objective -3.418789996500e-03, best bound -3.418789996500e-03, gap 0.0000%
Objective value with this comm detection algorithm -0.003418789995558764
Communities found at level 1:  1
Objective value with this comm detection algorithm -0.00017554955773673234
Communities found at level 1:  1

Processing market: semiconductor_giants
Returns shape: (10,)
Covariance matrix shape: (10, 10)
Correlation matrix shape: (10, 10)
Read LP format model from file temp.lp
Reading time = 0.00 seconds
obj: 1 rows, 10 columns, 10 nonzeros
Set parameter TimeLimit to value 300
Set parameter Threads to value 1
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 1 threads

Optimize a model with 1 rows, 10 columns and 10 nonzeros
Model fingerprint: 0xf6d516cc
Model has 55 quadratic objective terms
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [3e-03, 7e-03]
  QObjective range [2e-03, 1e-02]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+00, 5e+00]
Found heuristic solution: objective 0.0157502
Presolve time: 0.00s
Presolved: 46 rows, 55 columns, 145 nonzeros
Variable types: 0 continuous, 55 integer (55 binary)

Root relaxation: objective -8.649875e-03, 18 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   -0.00865    0   10    0.01575   -0.00865   155%     -    0s
H    0     0                       0.0036578   -0.00865   336%     -    0s
     0     0     cutoff    0         0.00366    0.00366  0.00%     -    0s

Cutting planes:
  Gomory: 1
  MIR: 30
  Zero half: 19
  RLT: 16
  BQP: 73

Explored 1 nodes (67 simplex iterations) in 0.07 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 2: 0.00365785 0.0157502

Optimal solution found (tolerance 1.00e-04)
Best objective 3.657846920500e-03, best bound 3.657846920500e-03, gap 0.0000%
Objective value with this comm detection algorithm 0.003657846920176476
Communities found at level 1:  1
Objective value with this comm detection algorithm 0.01188873279745787
Communities found at level 1:  1

Processing market: tech_titans
Returns shape: (10,)
Covariance matrix shape: (10, 10)
Correlation matrix shape: (10, 10)
Read LP format model from file temp.lp
Reading time = 0.00 seconds
obj: 1 rows, 10 columns, 10 nonzeros
Set parameter TimeLimit to value 300
Set parameter Threads to value 1
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 1 threads

Optimize a model with 1 rows, 10 columns and 10 nonzeros
Model fingerprint: 0xa6e1a69b
Model has 55 quadratic objective terms
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [4e-03, 8e-03]
  QObjective range [1e-03, 1e-02]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+00, 5e+00]
Found heuristic solution: objective -0.0009760
Presolve time: 0.00s
Presolved: 46 rows, 55 columns, 145 nonzeros
Variable types: 0 continuous, 55 integer (55 binary)

Root relaxation: objective -1.472517e-02, 11 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   -0.01473    0   10   -0.00098   -0.01473  1409%     -    0s
H    0     0                      -0.0026174   -0.01473   463%     -    0s
     0     0     cutoff    0        -0.00262   -0.00262  0.00%     -    0s

Cutting planes:
  Gomory: 1
  MIR: 30
  Zero half: 19
  RLT: 17
  BQP: 72

Explored 1 nodes (88 simplex iterations) in 0.08 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 2: -0.0026174 -0.000975966

Optimal solution found (tolerance 1.00e-04)
Best objective -2.617401998500e-03, best bound -2.617401998500e-03, gap 0.0000%
Objective value with this comm detection algorithm -0.002617401998283291
Communities found at level 1:  1
Objective value with this comm detection algorithm 0.0009563896267798175
Communities found at level 1:  1

Processing market: financial_giants
Returns shape: (10,)
Covariance matrix shape: (10, 10)
Correlation matrix shape: (10, 10)
Read LP format model from file temp.lp
Reading time = 0.00 seconds
obj: 1 rows, 10 columns, 10 nonzeros
Set parameter TimeLimit to value 300
Set parameter Threads to value 1
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 1 threads

Optimize a model with 1 rows, 10 columns and 10 nonzeros
Model fingerprint: 0xc99e3110
Model has 55 quadratic objective terms
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [6e-04, 5e-03]
  QObjective range [2e-03, 9e-03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+00, 5e+00]
Found heuristic solution: objective 0.0377614
Presolve time: 0.00s
Presolved: 46 rows, 55 columns, 145 nonzeros
Variable types: 0 continuous, 55 integer (55 binary)

Root relaxation: objective -1.761605e-03, 10 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   -0.00176    0   10    0.03776   -0.00176   105%     -    0s
H    0     0                       0.0264972   -0.00176   107%     -    0s
H    0     0                       0.0226048   -0.00176   108%     -    0s
H    0     0                       0.0089465   -0.00176   120%     -    0s
     0     0          -    0         0.00895    0.00895  0.00%     -    0s

Cutting planes:
  Gomory: 1
  MIR: 30
  Zero half: 19
  RLT: 16
  BQP: 73

Explored 1 nodes (56 simplex iterations) in 0.07 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 4: 0.00894654 0.0226048 0.0264972 0.0377614

Optimal solution found (tolerance 1.00e-04)
Best objective 8.946538597500e-03, best bound 8.946328406235e-03, gap 0.0023%
Objective value with this comm detection algorithm 0.008946538597924499
Communities found at level 1:  1
Objective value with this comm detection algorithm 0.01939462591260664
Communities found at level 1:  1

Processing market: retail_consumer
Returns shape: (10,)
Covariance matrix shape: (10, 10)
Correlation matrix shape: (10, 10)
Read LP format model from file temp.lp
Reading time = 0.00 seconds
obj: 1 rows, 10 columns, 10 nonzeros
Set parameter TimeLimit to value 300
Set parameter Threads to value 1
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 1 threads

Optimize a model with 1 rows, 10 columns and 10 nonzeros
Model fingerprint: 0x3ec698dc
Model has 55 quadratic objective terms
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e-03, 6e-03]
  QObjective range [6e-04, 7e-03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+00, 5e+00]
Found heuristic solution: objective -0.0028066
Presolve time: 0.00s
Presolved: 46 rows, 55 columns, 145 nonzeros
Variable types: 0 continuous, 55 integer (55 binary)

Root relaxation: objective -1.185302e-02, 9 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   -0.01185    0   10   -0.00281   -0.01185   322%     -    0s
H    0     0                      -0.0061704   -0.01185  92.1%     -    0s
H    0     0                      -0.0072817   -0.01185  62.8%     -    0s
     0     0     cutoff    0        -0.00728   -0.00728  0.00%     -    0s

Cutting planes:
  Gomory: 1
  MIR: 30
  Zero half: 19
  RLT: 18
  BQP: 71

Explored 1 nodes (49 simplex iterations) in 0.07 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 3: -0.00728167 -0.00617039 -0.00280662

Optimal solution found (tolerance 1.00e-04)
Best objective -7.281673852000e-03, best bound -7.281673852000e-03, gap 0.0000%
Objective value with this comm detection algorithm -0.007281673852742202
Communities found at level 1:  1
Objective value with this comm detection algorithm 0.0011331249750474726
Communities found at level 1:  1

Processing market: healthcare_leaders
Returns shape: (10,)
Covariance matrix shape: (10, 10)
Correlation matrix shape: (10, 10)
Read LP format model from file temp.lp
Reading time = 0.01 seconds
obj: 1 rows, 10 columns, 10 nonzeros
Set parameter TimeLimit to value 300
Set parameter Threads to value 1
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 1 threads

Optimize a model with 1 rows, 10 columns and 10 nonzeros
Model fingerprint: 0xda7d545f
Model has 55 quadratic objective terms
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e-03, 5e-03]
  QObjective range [1e-03, 4e-03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+00, 5e+00]
Found heuristic solution: objective -0.0022468
Presolve time: 0.00s
Presolved: 46 rows, 55 columns, 145 nonzeros
Variable types: 0 continuous, 55 integer (55 binary)

Root relaxation: objective -1.070502e-02, 11 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   -0.01071    0   10   -0.00225   -0.01071   376%     -    0s
H    0     0                      -0.0052649   -0.01071   103%     -    0s
     0     0     cutoff    0        -0.00526   -0.00526  0.00%     -    0s

Cutting planes:
  MIR: 30
  Zero half: 19
  RLT: 18
  BQP: 72

Explored 1 nodes (70 simplex iterations) in 0.09 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 2: -0.00526488 -0.00224677

Optimal solution found (tolerance 1.00e-04)
Best objective -5.264881927000e-03, best bound -5.264881927000e-03, gap 0.0000%
Objective value with this comm detection algorithm -0.00526488192631475
Communities found at level 1:  1
Objective value with this comm detection algorithm -0.0032707805919798133
Communities found at level 1:  1

Processing market: industrial_powerhouses
Returns shape: (10,)
Covariance matrix shape: (10, 10)
Correlation matrix shape: (10, 10)
Read LP format model from file temp.lp
Reading time = 0.01 seconds
obj: 1 rows, 10 columns, 10 nonzeros
Set parameter TimeLimit to value 300
Set parameter Threads to value 1
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 1 threads

Optimize a model with 1 rows, 10 columns and 10 nonzeros
Model fingerprint: 0x1ba1ef97
Model has 55 quadratic objective terms
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [8e-04, 4e-03]
  QObjective range [2e-03, 8e-03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+00, 5e+00]
Found heuristic solution: objective 0.0130186
Presolve time: 0.00s
Presolved: 46 rows, 55 columns, 145 nonzeros
Variable types: 0 continuous, 55 integer (55 binary)

Root relaxation: objective -2.260600e-03, 16 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   -0.00226    0   10    0.01302   -0.00226   117%     -    0s
H    0     0                       0.0125176   -0.00226   118%     -    0s
H    0     0                       0.0042775   -0.00226   153%     -    0s
     0     0     cutoff    0         0.00428    0.00428  0.00%     -    0s

Cutting planes:
  Gomory: 1
  MIR: 30
  Zero half: 19
  RLT: 17
  BQP: 72

Explored 1 nodes (44 simplex iterations) in 0.08 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 3: 0.00427751 0.0125176 0.0130186

Optimal solution found (tolerance 1.00e-04)
Best objective 4.277514698000e-03, best bound 4.277514698000e-03, gap 0.0000%
Objective value with this comm detection algorithm 0.00427751469909394
Communities found at level 1:  1
Objective value with this comm detection algorithm 0.015567501605736403
Communities found at level 1:  1

Processing market: defensive_plays
Returns shape: (10,)
Covariance matrix shape: (10, 10)
Correlation matrix shape: (10, 10)
Read LP format model from file temp.lp
Reading time = 0.00 seconds
obj: 1 rows, 10 columns, 10 nonzeros
Set parameter TimeLimit to value 300
Set parameter Threads to value 1
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 1 threads

Optimize a model with 1 rows, 10 columns and 10 nonzeros
Model fingerprint: 0x53367550
Model has 55 quadratic objective terms
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [7e-04, 3e-03]
  QObjective range [7e-06, 2e-03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+00, 5e+00]
Found heuristic solution: objective -0.0023840
Presolve time: 0.00s
Presolved: 46 rows, 55 columns, 145 nonzeros
Variable types: 0 continuous, 55 integer (55 binary)

Root relaxation: objective -8.026470e-03, 23 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   -0.00803    0   16   -0.00238   -0.00803   237%     -    0s
H    0     0                      -0.0046837   -0.00803  71.4%     -    0s
H    0     0                      -0.0047504   -0.00803  69.0%     -    0s
H    0     0                      -0.0055748   -0.00803  44.0%     -    0s
H    0     0                      -0.0061700   -0.00803  30.1%     -    0s
     0     0   -0.00630    0   17   -0.00617   -0.00630  2.08%     -    0s
     0     0     cutoff    0        -0.00617   -0.00617  0.00%     -    0s

Cutting planes:
  Gomory: 1
  Cover: 1
  Clique: 1
  MIR: 29
  Zero half: 7
  RLT: 8
  BQP: 42

Explored 1 nodes (71 simplex iterations) in 0.11 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 5: -0.00617003 -0.0055748 -0.0047504 ... -0.00238398

Optimal solution found (tolerance 1.00e-04)
Best objective -6.170034176000e-03, best bound -6.170034176000e-03, gap 0.0000%
Objective value with this comm detection algorithm -0.006170034176195616
Communities found at level 1:  1
Objective value with this comm detection algorithm -0.0052578247858780375
Communities found at level 1:  1

In [55]:
# Display the results dataframe
results_df

,Distribution,Market,Optimizer,Correlations,Covariances,Returns,DCT
0,MP Distribution,consumer_staples,None,"[[1.0, 0.47386620792483153, 0.6316363086512147...","[[0.0005528967935663235, 0.0002661030132532858...","[0.0019756254266453262, 0.0017536758753608581,...","([[1.0, 0.47386620792483153, 0.631636308651214..."
1,MP Distribution,consumer_staples,Gurobi,"[[1.0, 0.47386620792483153, 0.6316363086512147...","[[0.0005528967935663235, 0.0002661030132532858...","[0.0019756254266453262, 0.0017536758753608581,...","{'score': -0.003418789995558764, 'recombined_s..."
2,MP Distribution,consumer_staples,Dwave,"[[1.0, 0.47386620792483153, 0.6316363086512147...","[[0.0005528967935663235, 0.0002661030132532858...","[0.0019756254266453262, 0.0017536758753608581,...","{'score': -0.00017554955773673234, 'recombined..."
3,MP Distribution,semiconductor_giants,None,"[[1.0, 0.4722724555670802, 0.4972459461894452,...","[[0.003542835578726633, 0.0023177682025648147,...","[0.007259697150247052, 0.0038120867645143786, ...","([[1.0, 0.4722724555670802, 0.4972459461894452..."
4,MP Distribution,semiconductor_giants,Gurobi,"[[1.0, 0.4722724555670802, 0.4972459461894452,...","[[0.003542835578726633, 0.0023177682025648147,...","[0.007259697150247052, 0.0038120867645143786, ...","{'score': 0.003657846920176476, 'recombined_so..."
5,MP Distribution,semiconductor_giants,Dwave,"[[1.0, 0.4722724555670802, 0.4972459461894452,...","[[0.003542835578726633, 0.0023177682025648147,...","[0.007259697150247052, 0.0038120867645143786, ...","{'score': 0.01188873279745787, 'recombined_sol..."
6,MP Distribution,tech_titans,None,"[[1.0, 0.48763133498554195, 0.4455451713649541...","[[0.0014456847012178638, 0.0006075878078786981...","[0.004902196313674589, 0.004739169450291489, 0...","([[1.0, 0.48763133498554195, 0.445545171364954..."
7,MP Distribution,tech_titans,Gurobi,"[[1.0, 0.48763133498554195, 0.4455451713649541...","[[0.0014456847012178638, 0.0006075878078786981...","[0.004902196313674589, 0.004739169450291489, 0...","{'score': -0.002617401998283291, 'recombined_s..."
8,MP Distribution,tech_titans,Dwave,"[[1.0, 0.48763133498554195, 0.4455451713649541...","[[0.0014456847012178638, 0.0006075878078786981...","[0.004902196313674589, 0.004739169450291489, 0...","{'score': 0.0009563896267798175, 'recombined_s..."
9,MP Distribution,financial_giants,None,"[[1.0, 0.8632613381456855, 0.8676079586391919,...","[[0.001576439094087429, 0.0017417705303164324,...","[0.0023889045533935496, 0.0012539891378432974,...","([[1.0, 0.8632613381456855, 0.8676079586391919..."
10,MP Distribution,financial_giants,Gurobi,"[[1.0, 0.8632613381456855, 0.8676079586391919,...","[[0.001576439094087429, 0.0017417705303164324,...","[0.0023889045533935496, 0.0012539891378432974,...","{'score': 0.008946538597924499, 'recombined_so..."
11,MP Distribution,financial_giants,Dwave,"[[1.0, 0.8632613381456855, 0.8676079586391919,...","[[0.001576439094087429, 0.0017417705303164324,...","[0.0023889045533935496, 0.0012539891378432974,...","{'score': 0.01939462591260664, 'recombined_sol..."
12,MP Distribution,retail_consumer,None,"[[1.0, 0.5094034737091062, 0.5173195969907252,...","[[0.0006665528446817636, 0.0004739584315043416...","[0.0022802697927121174, 0.002301057765549372, ...","([[1.0, 0.5094034737091062, 0.5173195969907252..."
13,MP Distribution,retail_consumer,Gurobi,"[[1.0, 0.5094034737091062, 0.5173195969907252,...","[[0.0006665528446817636, 0.0004739584315043416...","[0.0022802697927121174, 0.002301057765549372, ...","{'score': -0.007281673852742202, 'recombined_s..."
14,MP Distribution,retail_consumer,Dwave,"[[1.0, 0.5094034737091062, 0.5173195969907252,...","[[0.0006665528446817636, 0.0004739584315043416...","[0.0022802697927121174, 0.002301057765549372, ...","{'score': 0.0011331249750474726, 'recombined_s..."
15,MP Distribution,healthcare_leaders,None,"[[1.0, 0.44964084829545514, 0.4856455759570758...","[[0.0012411811830122838, 0.000363799756276966,...","[0.004962649205389087, 0.002294022431808519, 0...","([[1.0, 0.44964084829545514, 0.485645575957075..."
16,MP Distribution,healthcare_leaders,Gurobi,"[[1.0, 0.44964084829545514, 0.4856455759570758...","[[0.0012411811830122838, 0.000363799756276966,...","[0.004962649205389087, 0.002294022431808519, 0...","{'score': -0.00526488192631475, 'recombined_so..."
17,MP Distribution,healthcare_leaders,Dwave,"[[1.0, 0.44964084829545514, 0.4856455759570758...","[[0.0012411811830122838, 0.000363799756276966,...","[0.004962649205389087, 0.002294022431808519, 0...","{'score': -0.0032707805919798133, 'recombined_..."
18,MP Distribution,industrial_powerhouses,None,"[[1.0, 0.516668434461206, 0.7135109739225585, ...","[[0.0017896477376539086, 0.0010213651269554175...","[0.002015348840199679, -0.0008076401486085086,...","([[1.0, 0.516668434461206, 0.7135109739225585,..."
19,MP Distribution,industrial_powerhouses,Gurobi,"[[1.0, 0.516668434461206, 0.7135109739225585, ...","[[0.0017896477376539086, 0.0010213651269554175...","[0.002015348840199679, -0.0008076401486085086,...","{'score': 0.00427751469909394, 'recombined_sol..."
20,MP Distribution,industrial_powerhouses,Dwave,"[[1.0, 0.516668434461206, 0.7135109739225585, ...","[[0.0017896477376539086, 0.0010213651269554175...","[0.002015348840199679, -0.0008076401486085086,...","{'score': 0.015567501605736403, 'recombined_so..."
21,MP Distribution,defensive_plays,None,"[[1.0, 0.473865960659252, 0.47184454754186017,...","[[0.0005703533990963529, 0.0002661029824125157...","[0.0017536758753608581, 0.0019756257672612805,...","([[1.0, 0.473865960659252, 0.47184454754186017..."
22,MP Distribution,defensive_plays,Gurobi,"[[1.0, 0.473865960659252, 0.47184454754186017,...","[[0.0005703533990963529, 0.0002661029824125157...","[0.0017536758753608581, 0.0019756257672612805,...","{'score': -0.006170034176195616, 'recombined_s..."
23,MP Distribution,defensive_plays,Dwave,"[[1.0, 0.473865960659252, 0.47184454754186017,...","[[0.0005703533990963529, 0.0002661029824125157...","[0.0017536758753608581, 0.0019756257672612805,...","{'score': -0.0052578247858780375, 'recombined_..."

### 2b: Shrinkage Estimator:

In [56]:
# Redoing imports with changed code:
from dcmppln.pipeline import Pipeline
from dcmppln.optimizer import GurobiOptimizer
from tests.input_data import InputData
from dcmppln.optimizer import SimulatedAnnealingDwave

In [57]:
# Loop through each market and analyze the stocks
# 2b Run:
for market_name, stocks in markets.items():
    print(f"\nProcessing market: {market_name}")
    
    # Distribution Type:
    distribution = "Shrinkage Estimator"
    
    # Download stock price data
    dataset = download_data(stocks, start_date, end_date, period_step)

    # Compute log returns
    log_period_returns = calculate_return(dataset)

    # Compute average returns for each stock (mean of log returns)
    returns = log_period_returns.mean().to_numpy()

    # Compute covariance matrix of log returns
    covariances = log_period_returns.cov().to_numpy()

    # Compute correlation matrix of log returns
    correlations = log_period_returns.corr().to_numpy()

    # Print output shapes for verification
    print("Returns shape:", returns.shape)  # (10,)
    print("Covariance matrix shape:", covariances.shape)  # (10, 10)
    print("Correlation matrix shape:", correlations.shape)  # (10, 10)")

    # No Optimizer Run
    p = Pipeline(
        correlations,
        covariances,
        returns,
    )
    dct = p.run()

    # Add results to dataframe
    results_df = pd.concat([results_df, pd.DataFrame([[distribution, market_name, "None", correlations, covariances, returns, dct]], 
                                                      columns=results_df.columns)], ignore_index=True)

    # Run with Gurobi Optimizer
    p = Pipeline(
        correlations,
        covariances,
        returns, 
        optimize_func=GurobiOptimizer()
    )
    dct = p.run(run_optimizer=True)

    # Add results to dataframe
    results_df = pd.concat([results_df, pd.DataFrame([[distribution, market_name, "Gurobi", correlations, covariances, returns, dct]], 
                                                      columns=results_df.columns)], ignore_index=True)

    # Run with D-Wave Simulated Annealing
    p = Pipeline(
        correlations,
        covariances,
        returns, 
        optimize_func=SimulatedAnnealingDwave()
    )
    dct = p.run(run_optimizer=True)

    # Add results to dataframe
    results_df = pd.concat([results_df, pd.DataFrame([[distribution, market_name, "Dwave", correlations, covariances, returns, dct]], 
                                                      columns=results_df.columns)], ignore_index=True)

Processing market: consumer_staples
Returns shape: (10,)
Covariance matrix shape: (10, 10)
Correlation matrix shape: (10, 10)
Read LP format model from file temp.lp
Reading time = 0.00 seconds
obj: 1 rows, 10 columns, 10 nonzeros
Set parameter TimeLimit to value 300
Set parameter Threads to value 1
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 1 threads

Optimize a model with 1 rows, 10 columns and 10 nonzeros
Model fingerprint: 0x08c5768f
Model has 55 quadratic objective terms
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e-03, 4e-03]
  QObjective range [6e-04, 4e-03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+00, 5e+00]
Found heuristic solution: objective -0.0032659
Presolve time: 0.00s
Presolved: 46 rows, 55 columns, 145 nonzeros
Variable types: 0 continuous, 55 integer (55 binary)

Root relaxation: objective -5.534066e-03, 25 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   -0.00553    0   16   -0.00327   -0.00553  69.5%     -    0s
H    0     0                      -0.0034188   -0.00553  61.9%     -    0s
     0     0     cutoff    0        -0.00342   -0.00342  0.00%     -    0s

Cutting planes:
  Gomory: 1
  MIR: 5
  Zero half: 12
  RLT: 8
  BQP: 42

Explored 1 nodes (64 simplex iterations) in 0.07 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 2: -0.00341878 -0.0032659

Optimal solution found (tolerance 1.00e-04)
Best objective -3.418783944000e-03, best bound -3.418783944000e-03, gap 0.0000%
Objective value with this comm detection algorithm -0.0034187839442253176
Communities found at level 1:  1
Objective value with this comm detection algorithm -0.0019427793804989574
Communities found at level 1:  1

Processing market: semiconductor_giants
Returns shape: (10,)
Covariance matrix shape: (10, 10)
Correlation matrix shape: (10, 10)
Read LP format model from file temp.lp
Reading time = 0.00 seconds
obj: 1 rows, 10 columns, 10 nonzeros
Set parameter TimeLimit to value 300
Set parameter Threads to value 1
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 1 threads

Optimize a model with 1 rows, 10 columns and 10 nonzeros
Model fingerprint: 0x544f824a
Model has 55 quadratic objective terms
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [3e-03, 7e-03]
  QObjective range [2e-03, 1e-02]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+00, 5e+00]
Found heuristic solution: objective 0.0157502
Presolve time: 0.00s
Presolved: 46 rows, 55 columns, 145 nonzeros
Variable types: 0 continuous, 55 integer (55 binary)

Root relaxation: objective -8.649873e-03, 18 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   -0.00865    0   10    0.01575   -0.00865   155%     -    0s
H    0     0                       0.0036578   -0.00865   336%     -    0s
     0     0     cutoff    0         0.00366    0.00366  0.00%     -    0s

Cutting planes:
  Gomory: 1
  MIR: 30
  Zero half: 19
  RLT: 16
  BQP: 73

Explored 1 nodes (67 simplex iterations) in 0.09 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 2: 0.00365784 0.0157502

Optimal solution found (tolerance 1.00e-04)
Best objective 3.657843123500e-03, best bound 3.657843123500e-03, gap 0.0000%
Objective value with this comm detection algorithm 0.003657843123566363
Communities found at level 1:  1
Objective value with this comm detection algorithm 0.01493984157891834
Communities found at level 1:  1

Processing market: tech_titans
Returns shape: (10,)
Covariance matrix shape: (10, 10)
Correlation matrix shape: (10, 10)
Read LP format model from file temp.lp
Reading time = 0.00 seconds
obj: 1 rows, 10 columns, 10 nonzeros
Set parameter TimeLimit to value 300
Set parameter Threads to value 1
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 1 threads

Optimize a model with 1 rows, 10 columns and 10 nonzeros
Model fingerprint: 0x3c9d4e05
Model has 55 quadratic objective terms
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [4e-03, 8e-03]
  QObjective range [1e-03, 1e-02]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+00, 5e+00]
Found heuristic solution: objective -0.0009760
Presolve time: 0.00s
Presolved: 46 rows, 55 columns, 145 nonzeros
Variable types: 0 continuous, 55 integer (55 binary)

Root relaxation: objective -1.472517e-02, 11 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   -0.01473    0   10   -0.00098   -0.01473  1409%     -    0s
H    0     0                      -0.0026174   -0.01473   463%     -    0s
     0     0     cutoff    0        -0.00262   -0.00262  0.00%     -    0s

Cutting planes:
  Gomory: 1
  MIR: 30
  Zero half: 19
  RLT: 17
  BQP: 72

Explored 1 nodes (88 simplex iterations) in 0.09 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 2: -0.00261739 -0.000975957

Optimal solution found (tolerance 1.00e-04)
Best objective -2.617394594500e-03, best bound -2.617394594500e-03, gap 0.0000%
Objective value with this comm detection algorithm -0.0026173945959132756
Communities found at level 1:  1
Objective value with this comm detection algorithm -0.001452549850378522
Communities found at level 1:  1

Processing market: financial_giants
Returns shape: (10,)
Covariance matrix shape: (10, 10)
Correlation matrix shape: (10, 10)
Read LP format model from file temp.lp
Reading time = 0.01 seconds
obj: 1 rows, 10 columns, 10 nonzeros
Set parameter TimeLimit to value 300
Set parameter Threads to value 1
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 1 threads

Optimize a model with 1 rows, 10 columns and 10 nonzeros
Model fingerprint: 0x3e0df06e
Model has 55 quadratic objective terms
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [6e-04, 5e-03]
  QObjective range [2e-03, 9e-03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+00, 5e+00]
Found heuristic solution: objective 0.0377614
Presolve time: 0.00s
Presolved: 46 rows, 55 columns, 145 nonzeros
Variable types: 0 continuous, 55 integer (55 binary)

Root relaxation: objective -1.761605e-03, 10 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   -0.00176    0   10    0.03776   -0.00176   105%     -    0s
H    0     0                       0.0264971   -0.00176   107%     -    0s
H    0     0                       0.0226048   -0.00176   108%     -    0s
H    0     0                       0.0089466   -0.00176   120%     -    0s
     0     0          -    0         0.00895    0.00895  0.00%     -    0s

Cutting planes:
  Gomory: 1
  MIR: 30
  Zero half: 19
  RLT: 16
  BQP: 73

Explored 1 nodes (56 simplex iterations) in 0.07 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 4: 0.00894655 0.0226048 0.0264971 0.0377614

Optimal solution found (tolerance 1.00e-04)
Best objective 8.946553951000e-03, best bound 8.946337245176e-03, gap 0.0024%
Objective value with this comm detection algorithm 0.008946553950387511
Communities found at level 1:  1
Objective value with this comm detection algorithm 0.019767269877852107
Communities found at level 1:  1

Processing market: retail_consumer
Returns shape: (10,)
Covariance matrix shape: (10, 10)
Correlation matrix shape: (10, 10)
Read LP format model from file temp.lp
Reading time = 0.00 seconds
obj: 1 rows, 10 columns, 10 nonzeros
Set parameter TimeLimit to value 300
Set parameter Threads to value 1
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 1 threads

Optimize a model with 1 rows, 10 columns and 10 nonzeros
Model fingerprint: 0xfa48ce78
Model has 55 quadratic objective terms
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e-03, 6e-03]
  QObjective range [6e-04, 7e-03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+00, 5e+00]
Found heuristic solution: objective -0.0028066
Presolve time: 0.00s
Presolved: 46 rows, 55 columns, 145 nonzeros
Variable types: 0 continuous, 55 integer (55 binary)

Root relaxation: objective -1.185302e-02, 9 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   -0.01185    0   10   -0.00281   -0.01185   322%     -    0s
H    0     0                      -0.0061704   -0.01185  92.1%     -    0s
H    0     0                      -0.0072817   -0.01185  62.8%     -    0s
     0     0     cutoff    0        -0.00728   -0.00728  0.00%     -    0s

Cutting planes:
  Gomory: 1
  MIR: 30
  Zero half: 19
  RLT: 18
  BQP: 71

Explored 1 nodes (49 simplex iterations) in 0.07 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 3: -0.00728167 -0.00617039 -0.00280662

Optimal solution found (tolerance 1.00e-04)
Best objective -7.281673808000e-03, best bound -7.281673808000e-03, gap 0.0000%
Objective value with this comm detection algorithm -0.007281673808523969
Communities found at level 1:  1
Objective value with this comm detection algorithm 0.003431354791592619
Communities found at level 1:  1

Processing market: healthcare_leaders
Returns shape: (10,)
Covariance matrix shape: (10, 10)
Correlation matrix shape: (10, 10)
Read LP format model from file temp.lp
Reading time = 0.00 seconds
obj: 1 rows, 10 columns, 10 nonzeros
Set parameter TimeLimit to value 300
Set parameter Threads to value 1
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 1 threads

Optimize a model with 1 rows, 10 columns and 10 nonzeros
Model fingerprint: 0xa9ba067b
Model has 55 quadratic objective terms
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e-03, 5e-03]
  QObjective range [1e-03, 4e-03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+00, 5e+00]
Found heuristic solution: objective -0.0022468
Presolve time: 0.00s
Presolved: 46 rows, 55 columns, 145 nonzeros
Variable types: 0 continuous, 55 integer (55 binary)

Root relaxation: objective -1.070502e-02, 11 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   -0.01071    0   10   -0.00225   -0.01071   376%     -    0s
H    0     0                      -0.0052649   -0.01071   103%     -    0s
     0     0     cutoff    0        -0.00526   -0.00526  0.00%     -    0s

Cutting planes:
  MIR: 30
  Zero half: 19
  RLT: 18
  BQP: 72

Explored 1 nodes (70 simplex iterations) in 0.06 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 2: -0.00526489 -0.00224677

Optimal solution found (tolerance 1.00e-04)
Best objective -5.264885727500e-03, best bound -5.264885727500e-03, gap 0.0000%
Objective value with this comm detection algorithm -0.005264885728662716
Communities found at level 1:  1
Objective value with this comm detection algorithm 0.0005862952053971929
Communities found at level 1:  1

Processing market: industrial_powerhouses
Returns shape: (10,)
Covariance matrix shape: (10, 10)
Correlation matrix shape: (10, 10)
Read LP format model from file temp.lp
Reading time = 0.00 seconds
obj: 1 rows, 10 columns, 10 nonzeros
Set parameter TimeLimit to value 300
Set parameter Threads to value 1
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 1 threads

Optimize a model with 1 rows, 10 columns and 10 nonzeros
Model fingerprint: 0xc4d3096b
Model has 55 quadratic objective terms
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [8e-04, 4e-03]
  QObjective range [2e-03, 8e-03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+00, 5e+00]
Found heuristic solution: objective 0.0130186
Presolve time: 0.00s
Presolved: 46 rows, 55 columns, 145 nonzeros
Variable types: 0 continuous, 55 integer (55 binary)

Root relaxation: objective -2.260604e-03, 16 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   -0.00226    0   10    0.01302   -0.00226   117%     -    0s
H    0     0                       0.0125176   -0.00226   118%     -    0s
H    0     0                       0.0042775   -0.00226   153%     -    0s
     0     0     cutoff    0         0.00428    0.00428  0.00%     -    0s

Cutting planes:
  Gomory: 1
  MIR: 30
  Zero half: 19
  RLT: 17
  BQP: 72

Explored 1 nodes (44 simplex iterations) in 0.07 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 3: 0.00427751 0.0125176 0.0130186

Optimal solution found (tolerance 1.00e-04)
Best objective 4.277505784500e-03, best bound 4.277505784500e-03, gap 0.0000%
Objective value with this comm detection algorithm 0.004277505784309294
Communities found at level 1:  1
Objective value with this comm detection algorithm 0.01578820856408915
Communities found at level 1:  1

Processing market: defensive_plays
Returns shape: (10,)
Covariance matrix shape: (10, 10)
Correlation matrix shape: (10, 10)
Read LP format model from file temp.lp
Reading time = 0.01 seconds
obj: 1 rows, 10 columns, 10 nonzeros
Set parameter TimeLimit to value 300
Set parameter Threads to value 1
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 1 threads

Optimize a model with 1 rows, 10 columns and 10 nonzeros
Model fingerprint: 0x427c93c1
Model has 55 quadratic objective terms
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [7e-04, 3e-03]
  QObjective range [7e-06, 2e-03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+00, 5e+00]
Found heuristic solution: objective -0.0023840
Presolve time: 0.00s
Presolved: 46 rows, 55 columns, 145 nonzeros
Variable types: 0 continuous, 55 integer (55 binary)

Root relaxation: objective -8.026471e-03, 23 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   -0.00803    0   16   -0.00238   -0.00803   237%     -    0s
H    0     0                      -0.0046837   -0.00803  71.4%     -    0s
H    0     0                      -0.0047504   -0.00803  69.0%     -    0s
H    0     0                      -0.0055748   -0.00803  44.0%     -    0s
H    0     0                      -0.0061700   -0.00803  30.1%     -    0s
     0     0   -0.00630    0   17   -0.00617   -0.00630  2.08%     -    0s
     0     0     cutoff    0        -0.00617   -0.00617  0.00%     -    0s

Cutting planes:
  Gomory: 1
  Cover: 1
  Clique: 1
  MIR: 29
  Zero half: 7
  RLT: 8
  BQP: 42

Explored 1 nodes (71 simplex iterations) in 0.10 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 5: -0.00617003 -0.0055748 -0.00475041 ... -0.00238398

Optimal solution found (tolerance 1.00e-04)
Best objective -6.170034040500e-03, best bound -6.170034040500e-03, gap 0.0000%
Objective value with this comm detection algorithm -0.006170034039281824
Communities found at level 1:  1
Objective value with this comm detection algorithm -0.003785368276536593
Communities found at level 1:  1

In [59]:
# Display the results dataframe
results_df = results_df.sort_values(by=["Market", "Optimizer"]).reset_index(drop=True)
results_df

,Distribution,Market,Optimizer,Correlations,Covariances,Returns,DCT
0,MP Distribution,consumer_staples,Dwave,"[[1.0, 0.47386620792483153, 0.6316363086512147...","[[0.0005528967935663235, 0.0002661030132532858...","[0.0019756254266453262, 0.0017536758753608581,...","{'score': -0.00017554955773673234, 'recombined..."
1,Shrinkage Estimator,consumer_staples,Dwave,"[[1.0, 0.473865960659252, 0.6316366670257212, ...","[[0.0005528972424157462, 0.0002661029824125156...","[0.0019756257672612805, 0.0017536758753608581,...","{'score': -0.0019427793804989574, 'recombined_..."
2,MP Distribution,consumer_staples,Gurobi,"[[1.0, 0.47386620792483153, 0.6316363086512147...","[[0.0005528967935663235, 0.0002661030132532858...","[0.0019756254266453262, 0.0017536758753608581,...","{'score': -0.003418789995558764, 'recombined_s..."
3,Shrinkage Estimator,consumer_staples,Gurobi,"[[1.0, 0.473865960659252, 0.6316366670257212, ...","[[0.0005528972424157462, 0.0002661029824125156...","[0.0019756257672612805, 0.0017536758753608581,...","{'score': -0.0034187839442253176, 'recombined_..."
4,MP Distribution,consumer_staples,None,"[[1.0, 0.47386620792483153, 0.6316363086512147...","[[0.0005528967935663235, 0.0002661030132532858...","[0.0019756254266453262, 0.0017536758753608581,...","([[1.0, 0.47386620792483153, 0.631636308651214..."
5,Shrinkage Estimator,consumer_staples,None,"[[1.0, 0.473865960659252, 0.6316366670257212, ...","[[0.0005528972424157462, 0.0002661029824125156...","[0.0019756257672612805, 0.0017536758753608581,...","([[1.0, 0.473865960659252, 0.6316366670257212,..."
6,MP Distribution,defensive_plays,Dwave,"[[1.0, 0.473865960659252, 0.47184454754186017,...","[[0.0005703533990963529, 0.0002661029824125157...","[0.0017536758753608581, 0.0019756257672612805,...","{'score': -0.0052578247858780375, 'recombined_..."
7,Shrinkage Estimator,defensive_plays,Dwave,"[[1.0, 0.4738657155922928, 0.47184454754186017...","[[0.0005703533990963529, 0.0002661025416857005...","[0.0017536758753608581, 0.001975625375834062, ...","{'score': -0.003785368276536593, 'recombined_s..."
8,MP Distribution,defensive_plays,Gurobi,"[[1.0, 0.473865960659252, 0.47184454754186017,...","[[0.0005703533990963529, 0.0002661029824125157...","[0.0017536758753608581, 0.0019756257672612805,...","{'score': -0.006170034176195616, 'recombined_s..."
9,Shrinkage Estimator,defensive_plays,Gurobi,"[[1.0, 0.4738657155922928, 0.47184454754186017...","[[0.0005703533990963529, 0.0002661025416857005...","[0.0017536758753608581, 0.001975625375834062, ...","{'score': -0.006170034039281824, 'recombined_s..."
10,MP Distribution,defensive_plays,None,"[[1.0, 0.473865960659252, 0.47184454754186017,...","[[0.0005703533990963529, 0.0002661029824125157...","[0.0017536758753608581, 0.0019756257672612805,...","([[1.0, 0.473865960659252, 0.47184454754186017..."
11,Shrinkage Estimator,defensive_plays,None,"[[1.0, 0.4738657155922928, 0.47184454754186017...","[[0.0005703533990963529, 0.0002661025416857005...","[0.0017536758753608581, 0.001975625375834062, ...","([[1.0, 0.4738657155922928, 0.4718445475418601..."
12,MP Distribution,financial_giants,Dwave,"[[1.0, 0.8632613381456855, 0.8676079586391919,...","[[0.001576439094087429, 0.0017417705303164324,...","[0.0023889045533935496, 0.0012539891378432974,...","{'score': 0.01939462591260664, 'recombined_sol..."
13,Shrinkage Estimator,financial_giants,Dwave,"[[1.0, 0.8632615041568401, 0.8676077974981384,...","[[0.0015764389489145545, 0.0017417709346871256...","[0.0023889041808288786, 0.0012539902028637074,...","{'score': 0.019767269877852107, 'recombined_so..."
14,MP Distribution,financial_giants,Gurobi,"[[1.0, 0.8632613381456855, 0.8676079586391919,...","[[0.001576439094087429, 0.0017417705303164324,...","[0.0023889045533935496, 0.0012539891378432974,...","{'score': 0.008946538597924499, 'recombined_so..."
15,Shrinkage Estimator,financial_giants,Gurobi,"[[1.0, 0.8632615041568401, 0.8676077974981384,...","[[0.0015764389489145545, 0.0017417709346871256...","[0.0023889041808288786, 0.0012539902028637074,...","{'score': 0.008946553950387511, 'recombined_so..."
16,MP Distribution,financial_giants,None,"[[1.0, 0.8632613381456855, 0.8676079586391919,...","[[0.001576439094087429, 0.0017417705303164324,...","[0.0023889045533935496, 0.0012539891378432974,...","([[1.0, 0.8632613381456855, 0.8676079586391919..."
17,Shrinkage Estimator,financial_giants,None,"[[1.0, 0.8632615041568401, 0.8676077974981384,...","[[0.0015764389489145545, 0.0017417709346871256...","[0.0023889041808288786, 0.0012539902028637074,...","([[1.0, 0.8632615041568401, 0.8676077974981384..."
18,MP Distribution,healthcare_leaders,Dwave,"[[1.0, 0.44964084829545514, 0.4856455759570758...","[[0.0012411811830122838, 0.000363799756276966,...","[0.004962649205389087, 0.002294022431808519, 0...","{'score': -0.0032707805919798133, 'recombined_..."
19,Shrinkage Estimator,healthcare_leaders,Dwave,"[[1.0, 0.44964049582281995, 0.4856459087863006...","[[0.0012411817056446034, 0.0003637995476887145...","[0.004962648358049588, 0.002294022431808519, 0...","{'score': 0.0005862952053971929, 'recombined_s..."
20,MP Distribution,healthcare_leaders,Gurobi,"[[1.0, 0.44964084829545514, 0.4856455759570758...","[[0.0012411811830122838, 0.000363799756276966,...","[0.004962649205389087, 0.002294022431808519, 0...","{'score': -0.00526488192631475, 'recombined_so..."
21,Shrinkage Estimator,healthcare_leaders,Gurobi,"[[1.0, 0.44964049582281995, 0.4856459087863006...","[[0.0012411817056446034, 0.0003637995476887145...","[0.004962648358049588, 0.002294022431808519, 0...","{'score': -0.005264885728662716, 'recombined_s..."
22,MP Distribution,healthcare_leaders,None,"[[1.0, 0.44964084829545514, 0.4856455759570758...","[[0.0012411811830122838, 0.000363799756276966,...","[0.004962649205389087, 0.002294022431808519, 0...","([[1.0, 0.44964084829545514, 0.485645575957075..."
23,Shrinkage Estimator,healthcare_leaders,None,"[[1.0, 0.44964049582281995, 0.4856459087863006...","[[0.0012411817056446034, 0.0003637995476887145...","[0.004962648358049588, 0.002294022431808519, 0...","([[1.0, 0.44964049582281995, 0.485645908786300..."
24,MP Distribution,industrial_powerhouses,Dwave,"[[1.0, 0.516668434461206, 0.7135109739225585, ...","[[0.0017896477376539086, 0.0010213651269554175...","[0.002015348840199679, -0.0008076401486085086,...","{'score': 0.015567501605736403, 'recombined_so..."
25,Shrinkage Estimator,industrial_powerhouses,Dwave,"[[1.0, 0.5166689596481682, 0.7135108680140972,...","[[0.001789644803140915, 0.001021365144270425, ...","[0.0020153490241170773, -0.0008076409090268334...","{'score': 0.01578820856408915, 'recombined_sol..."
26,MP Distribution,industrial_powerhouses,Gurobi,"[[1.0, 0.516668434461206, 0.7135109739225585, ...","[[0.0017896477376539086, 0.0010213651269554175...","[0.002015348840199679, -0.0008076401486085086,...","{'score': 0.00427751469909394, 'recombined_sol..."
27,Shrinkage Estimator,industrial_powerhouses,Gurobi,"[[1.0, 0.5166689596481682, 0.7135108680140972,...","[[0.001789644803140915, 0.001021365144270425, ...","[0.0020153490241170773, -0.0008076409090268334...","{'score': 0.004277505784309294, 'recombined_so..."
28,MP Distribution,industrial_powerhouses,None,"[[1.0, 0.516668434461206, 0.7135109739225585, ...","[[0.0017896477376539086, 0.0010213651269554175...","[0.002015348840199679, -0.0008076401486085086,...","([[1.0, 0.516668434461206, 0.7135109739225585,..."
29,Shrinkage Estimator,industrial_powerhouses,None,"[[1.0, 0.5166689596481682, 0.7135108680140972,...","[[0.001789644803140915, 0.001021365144270425, ...","[0.0020153490241170773, -0.0008076409090268334...","([[1.0, 0.5166689596481682, 0.7135108680140972..."
30,MP Distribution,retail_consumer,Dwave,"[[1.0, 0.5094034737091062, 0.5173195969907252,...","[[0.0006665528446817636, 0.0004739584315043416...","[0.0022802697927121174, 0.002301057765549372, ...","{'score': 0.0011331249750474726, 'recombined_s..."
31,Shrinkage Estimator,retail_consumer,Dwave,"[[1.0, 0.5094034737091062, 0.5173195969907252,...","[[0.0006665528446817636, 0.0004739584315043416...","[0.0022802697927121174, 0.002301057765549372, ...","{'score': 0.003431354791592619, 'recombined_so..."
32,MP Distribution,retail_consumer,Gurobi,"[[1.0, 0.5094034737091062, 0.5173195969907252,...","[[0.0006665528446817636, 0.0004739584315043416...","[0.0022802697927121174, 0.002301057765549372, ...","{'score': -0.007281673852742202, 'recombined_s..."
33,Shrinkage Estimator,retail_consumer,Gurobi,"[[1.0, 0.5094034737091062, 0.5173195969907252,...","[[0.0006665528446817636, 0.0004739584315043416...","[0.0022802697927121174, 0.002301057765549372, ...","{'score': -0.007281673808523969, 'recombined_s..."
34,MP Distribution,retail_consumer,None,"[[1.0, 0.5094034737091062, 0.5173195969907252,...","[[0.0006665528446817636, 0.0004739584315043416...","[0.0022802697927121174, 0.002301057765549372, ...","([[1.0, 0.5094034737091062, 0.5173195969907252..."
35,Shrinkage Estimator,retail_consumer,None,"[[1.0, 0.5094034737091062, 0.5173195969907252,...","[[0.0006665528446817636, 0.0004739584315043416...","[0.0022802697927121174, 0.002301057765549372, ...","([[1.0, 0.5094034737091062, 0.5173195969907252..."
36,MP Distribution,semiconductor_giants,Dwave,"[[1.0, 0.4722724555670802, 0.4972459461894452,...","[[0.003542835578726633, 0.0023177682025648147,...","[0.007259697150247052, 0.0038120867645143786, ...","{'score': 0.01188873279745787, 'recombined_sol..."
37,Shrinkage Estimator,semiconductor_giants,Dwave,"[[1.0, 0.4722724555670802, 0.49724584691593365...","[[0.003542835578726633, 0.0023177682025648147,...","[0.007259697150247052, 0.0038120867645143786, ...","{'score': 0.01493984157891834, 'recombined_sol..."
38,MP Distribution,semiconductor_giants,Gurobi,"[[1.0, 0.4722724555670802, 0.4972459461894452,...","[[0.003542835578726633, 0.0023177682025648147,...","[0.007259697150247052, 0.0038120867645143786, ...","{'score': 0.003657846920176476, 'recombined_so..."
39,Shrinkage Estimator,semiconductor_giants,Gurobi,"[[1.0, 0.4722724555670802, 0.49724584691593365...","[[0.003542835578726633, 0.0023177682025648147,...","[0.007259697150247052, 0.0038120867645143786, ...","{'score': 0.003657843123566363, 'recombined_so..."
40,MP Distribution,semiconductor_giants,None,"[[1.0, 0.4722724555670802, 0.4972459461894452,...","[[0.003542835578726633, 0.0023177682025648147,...","[0.007259697150247052, 0.0038120867645143786, ...","([[1.0, 0.4722724555670802, 0.4972459461894452..."
41,Shrinkage Estimator,semiconductor_giants,None,"[[1.0, 0.4722724555670802, 0.49724584691593365...","[[0.003542835578726633, 0.0023177682025648147,...","[0.007259697150247052, 0.0038120867645143786, ...","([[1.0, 0.4722724555670802, 0.4972458469159336..."
42,MP Distribution,tech_titans,Dwave,"[[1.0, 0.48763133498554195, 0.4455451713649541...","[[0.0014456847012178638, 0.0006075878078786981...","[0.004902196313674589, 0.004739169450291489, 0...","{'score': 0.0009563896267798175, 'recombined_s..."
43,Shrinkage Estimator,tech_titans,Dwave,"[[1.0, 0.4876313959010165, 0.4455454851285857,...","[[0.0014456856222373265, 0.0006075885329778928...","[0.0049021957512726646, 0.004739168860357627, ...","{'score': -0.001452549850378522, 'recombined_s..."
44,MP Distribution,tech_titans,Gurobi,"[[1.0, 0.48763133498554195, 0.4455451713649541...","[[0.0014456847012178638, 0.0006075878078786981...","[0.004902196313674589, 0.004739169450291489, 0...","{'score': -0.002617401998283291, 'recombined_s..."
45,Shrinkage Estimator,tech_titans,Gurobi,"[[1.0, 0.4876313959010165, 0.4455454851285857,...","[[0.0014456856222373265, 0.0006075885329778928...","[0.0049021957512726646, 0.004739168860357627, ...","{'score': -0.0026173945959132756, 'recombined_..."
46,MP Distribution,tech_titans,None,"[[1.0, 0.48763133498554195, 0.4455451713649541...","[[0.0014456847012178638, 0.0006075878078786981...","[0.004902196313674589, 0.004739169450291489, 0...","([[1.0, 0.48763133498554195, 0.445545171364954..."
47,Shrinkage Estimator,tech_titans,None,"[[1.0, 0.4876313959010165, 0.4455454851285857,...","[[0.0014456856222373265, 0.0006075885329778928...","[0.0049021957512726646, 0.004739168860357627, ...","([[1.0, 0.4876313959010165, 0.4455454851285857..."

In [60]:
# Save the results dataframe to a CSV file
csv_filename = "market_analysis_results.csv"
results_df.to_csv(csv_filename, index=False)
print(f"CSV file saved: {csv_filename}")

CSV file saved: market_analysis_results.csv